server.port: 8999


#view
spring.mvc.view:
  prefix: /WEB-INF/views/
  suffix: .jsp


#mybatis
#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapping.xml
  typeAliasesPackage: com.og.oms.model #实体扫描，多个package用逗号或者分号分隔
  typeEnumsPackage: com.og.oms.enums
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
  global-config:
    id-type: 0 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 2 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-column-underline: true #驼峰下划线转换
    refresh-mapper: true #刷新mapper 调试神器
    capital-mode: true #数据库大写下划线转换
    logic-delete-value: 0 #逻辑删除配置
    logic-not-delete-value: 1 #逻辑删除配置
#    meta-object-handler: com.baomidou.springboot.xxx #自定义填充策略接口实现
#    sql-injector: com.baomidou.springboot.xxx #自定义SQL注入器
#    key-generator: com.baomidou.springboot.xxx #序列接口实现类配置


# jdbc_config
spring.datasource:
    url: jdbc:postgresql://192.168.224.128:5432/posystem
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwe123
    type: com.alibaba.druid.pool.DruidDataSource


#log
logging:
  config: classpath:logback.xml
  path: D:\jeff-project\log


#logging:
#  path: E:\springbootlog #/home/_xyy_/output/SpringBootDemo/logs
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    hibernate: ERROR
#logging.file=demo.log


# 设置邮箱主机
spring.mail:
  host: smtp.qq.com
  username: 用户名 # 设置用户名
  password: 密码 # 设置密码
# 设置是否需要认证，如果为true,那么用户名和密码就必须的，
#如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
spring.mail.properties.mail.smtp:
  auth: true
# STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
  enable: true
  starttls.required: true


# 自定义参数
spring.email.sender: test@qq.com # 邮件发送者

